{
 "title": "OpenDTU",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Ertrag Gesamt",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opendtu_YieldTotal{type=\"AC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ertrag aktuell",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opendtu_YieldDay{type=\"AC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leistung Gesamt AC",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opendtu_Power{type=\"AC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leistung Einzelpanele",
   "type": "piechart",
   "description": "Spitzenleistung der Panele",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opendtu_Power{type=\"DC\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Kenndaten",
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 20, "y": 0 },
   "options": {
    "content": "```\nInbetriebnahme: xx.yy.20zz\nInverter: Hoymiles HM-800\nInverter #: secret\n```"
   },
   "content": "\n# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n\n\n\n"
  },
  {
   "title": "Ertrag heute",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "opendtu_YieldDay{type=\"AC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Effizienz Inverter",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 5, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "opendtu_Efficiency", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Spannung DC",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 6, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "opendtu_Voltage{type=\"AC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "timeseries",
   "description": "in ^C",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "opendtu_Temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Leistung Verlauf",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "opendtu_PowerDC", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sonnenenergie",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    { "expr": "opendtu_Irradiation", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AC Frequenz",
   "type": "timeseries",
   "description": "Gleichstrom Frequenz",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    { "expr": "opendtu_Frequency", "legendFormat": "__auto" }
   ]
  }
 ]
}